### Tipo de datos 
### Númericos 
### Hay tres tipos de datos númericos los cuales son:
### 1:foat 
### 2:integer
### 3:complejos

## Float
### Es el más importante tipo de dato scalar para el análisis númerico. Para ingresar un tipo de dato númerico de la clasefloat debemos incluir primero un "." (punto) en la expresión y para saber si una variable "x" es float se le pone type(x): 

In [1]:
x=1.2

In [2]:
type(x)

float

In [46]:
y=1

In [47]:
type(y)

int

In [48]:
y=float(y)

In [49]:
y

1.0

In [8]:
type(y)

float

## Integer

### Almacena números usando una representación exacta, de modo que no se necesita una aproximación. El costo de la representación exacta es que el tipo de datos enteros no puede expresar nada que no sea un entero, lo que hace que los enteros tengan un uso limitado en la mayoría de los trabajos numéricos. 

In [11]:
x=1

In [13]:
type(x)

int

In [38]:
y=1.2

In [39]:
type(y)

float

In [40]:
y

1.2

In [41]:
y=int(y)

In [42]:
type(y)

int

In [43]:
print(y)

1


## String

### Strings son delimitados usando citas (”) o comillas ("")pero nou sandola combinación de ellas, es decir, (’") en un único string, excepto cuando se usa para expresar una citación.


In [28]:
 x = 'abc' 

In [29]:
type(x)

str

In [34]:
 y = '"Es una cita!"' 

In [36]:
print(y)

"Es una cita!"


### Substrings dentro de un string puede ser accedidos usand slicing. Slicing usa [ ] para contener los indices de los caracters en un string, donde el primer indice es 0, y el último es n-1, asumiendo que el string tiene n letras.


In [52]:
 text = 'Hola clase' 

In [53]:
text

'Hola clase'

In [54]:
# la funcion len nos ayuda a ver el rango de una variable
len(text)

10

In [66]:
#String entero
text[:]

'Hola clase'

In [65]:
# text[i] : Caracter en la posición i 
text[5]

'c'

In [67]:
# text[i:] : Caracter en la posición i hasta el final 
text[6:]

'lase'

In [68]:
# text[:i] : Caracter en la posición 0 hasta i 
text[:6]

'Hola c'

In [69]:
# text[j:i] : Caracter en la posición j hasta i 
text[1:6]


'ola c'

In [70]:
# text[j:i:m] : Caracter j, j+m,..j+ m|(i-m-j)/m| 
text[1:10:2]


'oacae'

In [71]:
# text[-i] : Caracter n-i 
text[-5]


'c'

In [73]:
# text[-i:] : Caracter n-i,..n-1 
text[-5:]

'clase'

In [74]:
# text[:-i] : Caracter 0,..., n-i-1 
text[:-5]

'Hola '

## Boolean 
### Son usado para representar verdadero o falso, usando las palabras reservadas True y False.


In [75]:
x = True 
type(x)


bool

In [76]:
x = bool(1)
x

True

In [77]:
x = bool(0)
x


False

## Lists
### Un list es una recolección de otros objetos(floats, integers, complex, strings e incluso otras listas) Son esenciales para programar en Python y son usados para almacenar colecciones de otros valores. Son construidos con "[ ]" y valores son separados por comas ",".


In [80]:
x=[1,2,3,4]
type(x)

list

In [81]:
x

[1, 2, 3, 4]

In [82]:
# Listas de listas 
x = [[1,2,3,4], [5,6,7,8]]
x

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [83]:
#Listas no rectangulares
x = [[1,2,3,4] , [5,6,7]]
x

[[1, 2, 3, 4], [5, 6, 7]]

In [84]:
#Listas mezcladas
x = [1,1.0,1+0j,'one',None,True]

In [85]:
x

[1, 1.0, (1+0j), 'one', None, True]

In [88]:
x = [1,2,3,4,5,6,7,8,9]

In [89]:
x[2]

3

### List pueden ser multidimensional, y slicing puede ser hecho directamente en dimensiones mayores a 1. Por ejemplo, consideremos el siguiente list x = [[1,2,3,4], [5,6,7,8]]. Si un solo indice es usado, x[0] retornará la primera lista, y x[1] retornará la segunda lista. Ya que la lista retornada por x[0] es sliceable (dividible), Podemos dividirla directamente usando, por ejemplo, x[0][0] o x[0][1:4]

In [100]:
#selecciono la primera lista de la lista
x = [[1,2,3,4], [5,6,7,8]]
x[0]

[1, 2, 3, 4]

In [101]:
#seleccionamos de la primera lista de la lista el primer elemento 
x[0][0]

1

In [102]:
# Esta funcion nos ayuda a agregar un numero al final de la lista
# list.append(value)
x.append(10)

In [103]:
x

[[1, 2, 3, 4], [5, 6, 7, 8], 10]

In [104]:
#agregamos como otro elemneto una lista nueva
x.append([1,2,3])

In [105]:
x

[[1, 2, 3, 4], [5, 6, 7, 8], 10, [1, 2, 3]]

In [106]:
len(x)

4

In [108]:
#agregamos los elementos de una lista a la lista nueva
x.extend([11,12,13])

In [109]:
x

[[1, 2, 3, 4], [5, 6, 7, 8], 10, [1, 2, 3], 11, 12, 13]

In [110]:
#eleminamos la posicion
x.pop(1) 

[5, 6, 7, 8]

In [111]:
x

[[1, 2, 3, 4], 10, [1, 2, 3], 11, 12, 13]

In [114]:
#eliminamos el elemento
x.remove(10) 

In [115]:
x

[[1, 2, 3, 4], [1, 2, 3], 11, 12, 13]

In [118]:
#otra forma de eliminar una posicion es 
x = [0,1,2,3,4,5,6,7,8,9] 
del x[0] 

In [119]:
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [120]:
del x[:3]
x


[4, 5, 6, 7, 8, 9]

## Tuple

### Un tuple es identico a un list, salvo con una diferencia, que un tuple no puede ser cambiado una vez que se crea. No es posible agregar, remover o reemplazar elementos en un tiple. Pero, si un tuple contiene un tipo de dato mutable, por ejemplo, un list, ese tipo de dato puede ser alterado.Tuples son construidos usando parentesis "()".


In [121]:
x =(0,1,2,3,4,5,6,7,8,9) 
type(x)

tuple

In [122]:
x[-10:-5]

(0, 1, 2, 3, 4)

In [125]:
x = list(x)
type(x)

list

In [124]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [126]:
#El contenido puede ser cambiado 
x= ([1,2],[3,4])
x[0][1] = -10 
x

([1, -10], [3, 4])

##  Dict 
### Los Dicts son usados para funciones como optimizers. Están compuestos de keys (palabras) y values(definiciones). Los keys deben ser tipo de datos inmutable y único(por ejemplo, strings, integers, tuples que contengan tipos inmutables) y values pueden contener cualquier tipo de data válido en Python.

In [127]:
data = {'age': 34, 'children' : [1,2], 1: 'apple'}
type(data)


dict

In [128]:
data['age']

34

In [129]:
#Podemos agregar nuevos keys y values. 
data['name'] = 'abc'

In [130]:
data

{'age': 34, 'children': [1, 2], 1: 'apple', 'name': 'abc'}

In [132]:
 #Podemos cambiar
data['age'] = 'ade'

In [133]:
data

{'age': 'ade', 'children': [1, 2], 1: 'apple', 'name': 'abc'}

In [134]:
#eliminar un dict
del data['age']
data

{'children': [1, 2], 1: 'apple', 'name': 'abc'}

## Arrays y Matrices

La diferencia entre estos dos tipos de datos son:
Arrays puede tener 1, 2, 3 más dimensiones, y las matrices siempre tienen 2 dimensiones. Esto
significa que un vector 1xn almacenado como un array tiene dimensión 1 y n elementos, mientras
que el mismo vector almacenado como una matriz tiene 2 dimensiones donde el tamaño de las
dimensiones son 1 y n.
Los operadores matemáticos standards sobre arrays operan elemento por elemento. No es el
caso para matrces, donde la multiplicación (*) sigue las reglas del algebra lineal. Arrays pueden
ser multiplcados usando el simbolo @.
Arrays son más comunes que las matrices, y todas las funciones son testeado con arrays. La
misma función deberia funcionar con matrices pero hay la posibilidad de un bug cuando uses
matrices.
Arrays son más comunes que las matrices, y todas las funciones son testeado con arrays. La
misma función deberia funcionar con matrices pero hay la posibilidad de un bug cuando uses
matrices.

## Array

In [2]:
import numpy as np
from numpy import array
from pylab import*

In [6]:
x = [0.0, 1, 2, 3, 4]
y=array(x)

In [7]:
y

array([0., 1., 2., 3., 4.])

In [8]:
type(y)

numpy.ndarray

In [9]:
y = array([[0.0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [10]:
y

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [11]:
shape(y)

(2, 5)

In [46]:
y = array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [47]:
y

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
shape(y)

(2, 2, 2)

## Matrices

Matrices son un subconjunto de arrays y se comporta de manera identica a ellos. Las dos importante
diferencias son:
Arrays puede tener 1, 2, 3 más dimensiones, y las matrices siempre tienen 2 dimensiones. Esto
significa que un vector 1xn almacenado como un array tiene dimensión 1 y n elementos, mientras
que el mismo vector almacenado como una matriz tiene 2 dimensiones donde el tamaño de las
dimensiones son 1 y n.
Matrices siempre tienen dos dimensiones.
Matrices sigue las reglas del algebra lineal por *.
Arrays de 1 y 2 dimensiones pueden ser copiado a una matriz llamando la matriz sobre un
array. Alternativamente, mat o asmatrix provee un método más rápido para coercionar un array a
comportarse como una matriz sin copiar cualquier dato.

In [48]:
x = [0.0, 1, 2, 3, 4] # Cualquier float hace otro float
y = array(x)
type(y)

numpy.ndarray

In [49]:
a=y * y # Elemento-por-elemento
type(y)

numpy.ndarray

In [50]:
a

array([ 0.,  1.,  4.,  9., 16.])

In [17]:
z = np.asmatrix(x)
type(z)

numpy.matrixlib.defmatrix.matrix

In [21]:
z * z # Error

ValueError: shapes (1,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

## Arrays de una dimension

Un vector:
x = [1 2 3 4 5]
Es ingresado como un array de una dimensión usando:

In [51]:
x=array([1.0, 2.0, 3.0, 4.0, 5.0])

In [52]:
ndim(x)

1

In [53]:
#Una matriz es siempre dos dimensiones
x=matrix([1.0,2.0,3.0,4.0,5.0])
x

matrix([[1., 2., 3., 4., 5.]])

Note que la representación de la matriz usa listas anidadas ([[]]) para enfatizar la estructura de
dos dimensiones de todas las matrices. El vector columna es:
    Es ingresado como una matriz o un array de dos dimensiones usando un set de listas anidadas.

In [54]:
x=matrix([[1.0],[2.0],[3.0],[4.0],[5.0]])
x

matrix([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

In [58]:
x = array([[1.0],[2.0],[3.0],[4.0],[5.0]])
ndim(x)
x

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]])

## Arrays de dos dimensiones

Matrices y arrays de dos dimensiones son filas de columnas and 2-dimensional arrays are rows of
columns

In [59]:
x = array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])
ndim(x)

2

## Concatenación

Concatenación es el proceso por el que un vector o matriz está añadido a otro. Arrays y matrices
pueden ser concatenados horizontalmente o verticalmente. Por ejemplo:

Si queremos concatenar x e y como elementos de un nuevo array podemos hacerlo con la función
concatenate. Los inputos para concatenar deben ser agrupados en un tuple y el argumento
axis que especifica si el array es vertical (axis = 0) u horizontal(axis = 1).

In [68]:
x = array([[1.0,2.0],[3.0,4.0]])
y = array([[5.0,6.0],[7.0,8.0]])
a = array([[8.0,9.0],[2.0,3.0]])
z = concatenate((x,y),axis = 0)
z

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [66]:
z = concatenate((y,x,a),axis = 1)
z

array([[5., 6., 1., 2., 8., 9.],
       [7., 8., 3., 4., 2., 3.]])

Concatenar es equivalente a programar formas de bloques de matriz en algebra lineal.
Alternativamente, las funciones vstack y hstack pueden ser usado para arrays verticales y horizontales,
respectivamente.

In [67]:
z = vstack((x,y)) # Lo mismo que z = concatenate((x,y),axis = 0)
z

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [36]:
z = hstack((x,y)) # Lo mismo que z = concatenate((x,y),axis = 1)
z

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

## Accediendo a elementos de Arrays

Cuatro métodos están disponibles para acceder a elementos contenidos dentro de un array: scalar
selection, slicing, numerical indexing and logical indexing. Los primeros dos son los más simples.

## Scalar Selection

Es implementado usando [i] para arrays de una dimensión, [i,j] para arrays de dos dimensiones y
[i1,i2,..,in] para arrays de n dimensiones. Como toda indexación en Python, selección está basada
en 0, por lo que [0] es el primer elemento en un array de 1 dimensión, [0,0] para 2 dimensiones y
así.

In [69]:
x = array([1.0,2.0,3.0,4.0,5.0])
x[0]

1.0

In [77]:
x = array([[1.0,2,3],[4,5,6]])
x[1,2]

6.0

## Array slicing

Arrays slicing es idéntico a list slicing. Slicing básico de arrays de 1-dimensión es idéntico a slicing
un simple list.

In [3]:
x = array([1.0,2.0,3.0,4.0,5.0])

In [4]:
y = x[:]

In [5]:
y

array([1., 2., 3., 4., 5.])

In [6]:
y = x[:2]

In [7]:
y

array([1., 2.])

Slicing básico de arrays de 2-dimensión es idéntico a slicing un simple list. La primera dimensión
específica la fila o filas del slice y la segunda dimensión específica la columna o las columnas.
Note que la sintaxis del slice de dos dimensiones y[a:b,c:d] es lo mismo que y[a:b,:][:,c:d]
or y[a:b][:,c:d], En el caso donde solo el slicing de la fila es necesario y[a:b], es el equivalente de
y[a:b,:].

In [8]:
y = array([[0.0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
y

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [9]:
y[:1,:] # Fila 0, todas las columnas

array([[0., 1., 2., 3., 4.]])

In [10]:
y[:1] # Lo mismo que y[:1,:]

array([[0., 1., 2., 3., 4.]])

In [11]:
y[:,:1] # Todas las filas, columna 0

array([[0.],
       [5.]])

In [14]:
y[:,3:] # Todas las filas, columnas 3 y 4

array([[3., 4.],
       [8., 9.]])

In [12]:
y[:1,0:3] # Fila 0,las columnas de 0 a 2.

array([[0., 1., 2.]])

In [13]:
y[:1][:,0:3]

array([[0., 1., 2.]])

## Asignación usando Slicing

Slicing y scalar selection pueden ser usado para asignar arrays que tienen la misma dimensión
como el slice.

In [20]:
x = array([[0.0]*3]*3) # *3 repite la lista 3 veces.
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
x[0,:] = array([1.0, 2.0, 3.0])
x

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
x[1,1] = pi
x

array([[1.        , 2.        , 3.        ],
       [0.        , 3.14159265, 0.        ],
       [0.        , 0.        , 0.        ]])

## Funciones matemáticas

In [24]:
x = randn(3,4) #Matriz aleatoria 3x4

In [25]:
x

array([[ 0.88117592,  0.26416365, -2.78125424,  0.39810568],
       [-0.49107765, -2.14484128,  1.38662849,  1.00280452],
       [ 1.57977839,  0.53098475, -0.82761497,  0.17120423]])

In [27]:
sum(x) # Suma de todos los elementos

-0.029942493386030722

In [28]:
sum(x, 0) #Suma de todo por columna.

array([ 1.96987666, -1.34969287, -2.22224072,  1.57211444])

In [29]:
0.88117592-0.49107765+1.57977839

1.96987666

In [30]:
sum(x, 1) # A través de columnas

array([-1.23780898, -0.24648592,  1.45435241])

In [37]:
x

array([[ 0.88117592,  0.26416365, -2.78125424,  0.39810568],
       [-0.49107765, -2.14484128,  1.38662849,  1.00280452],
       [ 1.57977839,  0.53098475, -0.82761497,  0.17120423]])

In [42]:
log(x)

C:\Users\HP 360\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[-0.12649799, -1.33118646,         nan, -0.92103777],
       [        nan,         nan,  0.32687525,  0.0028006 ],
       [ 0.45728458, -0.63302197,         nan, -1.76489811]])

In [43]:
log10(x)

C:\Users\HP 360\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([[-0.05493738, -0.57812694,         nan, -0.40000162],
       [        nan,         nan,  0.14196012,  0.00121628],
       [ 0.19859617, -0.27491795,         nan, -0.76648551]])

In [44]:
sqrt(x)

C:\Users\HP 360\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[0.93870971, 0.51396853,        nan, 0.63095617],
       [       nan,        nan, 1.17755191, 1.00140128],
       [1.25689236, 0.72868701,        nan, 0.41376833]])

In [49]:
square(x)

array([[0.776471  , 0.06978244, 7.73537515, 0.15848814],
       [0.24115726, 4.60034411, 1.92273857, 1.00561691],
       [2.49569978, 0.28194481, 0.68494654, 0.02931089]])

In [53]:
0.88117592**3

0.6842075495299624

In [51]:
x**3

array([[ 6.84207545e-01,  1.84339834e-02, -2.15140450e+01,
         6.30950276e-02],
       [-1.18426940e-01, -9.86700793e+00,  2.66612407e+00,
         1.00843719e+00],
       [ 3.94265259e+00,  1.49708393e-01, -5.66872007e-01,
         5.01814807e-03]])

In [50]:
abs(x)

array([[0.88117592, 0.26416365, 2.78125424, 0.39810568],
       [0.49107765, 2.14484128, 1.38662849, 1.00280452],
       [1.57977839, 0.53098475, 0.82761497, 0.17120423]])

In [64]:
x = repeat(randn(3),(2))
x

array([ 0.61882261,  0.61882261, -1.20203943, -1.20203943, -0.48313135,
       -0.48313135])

In [65]:
unique(x)

array([-1.20203943, -0.48313135,  0.61882261])

In [66]:
max(x) 

0.6188226101669896

In [69]:
min(x)

-1.2020394324181112

## Condicional If

In [1]:
#condicional IF
#Si (condición)entonces:
# lo que queramos 
#Cualquier otro caso:
#Lo que queramos
edad =17

if edad>18:
    print (" si es mayor de edad")
else:
    print ("no es mayor de edad")

no es mayor de edad


In [2]:
# if anidado 
edad =19
pago= False
if edad>18:
    print (" si es mayor de edad")
    if pago == True:
        print ("Entonces eres mayor y pagaste")
    else: 
        print ("Eres mayor y no pagaste")
else:
    print ("no es mayor de edad")

 si es mayor de edad
Eres mayor y no pagaste


In [3]:
# Bluque llamado while(mientras)
numero =1
while (numero<100):
    print ("el valor de numero es:",numero)
    numero=numero+1

el valor de numero es: 1
el valor de numero es: 2
el valor de numero es: 3
el valor de numero es: 4
el valor de numero es: 5
el valor de numero es: 6
el valor de numero es: 7
el valor de numero es: 8
el valor de numero es: 9
el valor de numero es: 10
el valor de numero es: 11
el valor de numero es: 12
el valor de numero es: 13
el valor de numero es: 14
el valor de numero es: 15
el valor de numero es: 16
el valor de numero es: 17
el valor de numero es: 18
el valor de numero es: 19
el valor de numero es: 20
el valor de numero es: 21
el valor de numero es: 22
el valor de numero es: 23
el valor de numero es: 24
el valor de numero es: 25
el valor de numero es: 26
el valor de numero es: 27
el valor de numero es: 28
el valor de numero es: 29
el valor de numero es: 30
el valor de numero es: 31
el valor de numero es: 32
el valor de numero es: 33
el valor de numero es: 34
el valor de numero es: 35
el valor de numero es: 36
el valor de numero es: 37
el valor de numero es: 38
el valor de numero es

In [7]:
#Funciones
def saludo(nombre):
    print("hola",nombre)
    
saludo("alexis")
# aqui pasamos un valor fijo


hola alexis


In [14]:
#regresar un valor
def sumar(numero1,numero2):
    return numero1+numero2
#valor=sumar(5,5) y poner en print valor (es otra opción)
print (sumar(5,5))

10


## Help

In [15]:
tupla=(2,4,5)
help(tupla)

Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /)
 |      Return self<